### ISSUE TITLE
Remove extra line from documentation

### ISSUE THREAD

**Issue by ilyakooo0** [dredozubov/xsd-isogen#15]
Currently if there is a `xs:documentation` tag present, the contents are inserted as haddock documentation above the xml definition. However, after the comment an extra empty comment line is sometimes added `-- `, which is not desirable. I have not been able to figure out when the extra comment gets inserted.

Furthermore, it probably makes sense to strip trailing whitespace from all comments.

**Comment by Yuras** [comment]
Fixed by https://github.com/typeable/xsd-isogen/pull/17
